Feat/files guides res
LiteraExcurs/backend pull request #12
Opened 2023-10-25 11:34 UTC by Gyxer513

Добавил логику добавления данных о файлах в базу.
Добавил всю логику по гидам.
Добавил серв файлов беком, ссылки записываются в базу.

2023-10-26 10:28 UTC, vierim requested changes
Хорошая работа. Надо внести некоторые правки:
- если папки /uploads/activities не существует, то бек падает с ошибкой. Нужно создавать такую папку автоматически или дать описание к преокту, что перед стартом такую папку нужно создать вручную;
- нужно исправить описания всех моделей, так как сейчас они описаны с использованием некорректной методики (используется class-validator);
- при работе с файлами ошибки могут возникнуть на любом этапе, а сейчас они никак не обрабатываются, что вызывает падение сервака каждый раз;
- сейчас администратор сайта может нечайно затереть файлы, если будет использовать одинаковое название. Это создает некую непредсказуемость. Лучше все таки делать уникальные имена файлов.

Вполне возможно, что это не все замечания, которые можно сейчас найти в коде. Но так как они очень важные, не вижу смысла дальше проводить код ревью, пока не будет исправлений.

2023-10-26 10:28 UTC, vierim commented on src/files/dto/create-file.dto.ts
Не вижу причин для таких жестких ограничений на поле name для файла. Я так понимаю, поле name - это название файла, которое будет отображаться в админке сайта. Поэтому называть его можно так, как удобно администратору - и русскими буквами с пробелом, и длинее 20 символов.

2023-10-26 10:28 UTC, vierim commented on src/files/entities/file.entity.ts
В данной сущности ограничение на поле name еще строже, чем в DTO. Во-первых, это не правильно само по себе, во-вторых, опять же, не вижу причин для этого.

2023-10-26 10:28 UTC, vierim commented on src/files/files.service.ts
> +      const webpFile = await this.convertToWepP(file.buffer);
Нужна обрабатывать ошибку, которая возникает при отправке файла, который не может быть конкертирован в webP. Сервер не должен при этом падать.

Возможно, есть смысл добавить валидацию еще на уровне контроллера - https://docs-nestjs.netlify.app/techniques/file-upload#file-validation

2023-10-26 10:28 UTC, vierim commented on src/files/files.controller.ts
> +    return this.filesService.saveFile(saveArray, 'activities');
По сути вторым параметром мы можем прокинуть в функцию сохранения любое название дирректории. Лучше определить их как константы и работать уже с ними.

2023-10-26 10:28 UTC, vierim commented on src/files/files.service.ts
> +  async createRecord(query: CreateFileDto): Promise<File> {
Название аргумента функции `query` не отражает его суть. Это все таки набор каких-то данных, а не запрос.

2023-10-26 10:28 UTC, vierim commented on package.json
> +    "eslint-plugin-react-hooks": "^4.3.0",
Не совсем понимаю, зачем нам плагины в EsLint для фронтента на беке - react, react-hooks, jsx.

2023-10-26 10:28 UTC, vierim commented on src/guides/entities/guide.entity.ts
> +  completed: number;
Добавь, пожалуйста, минимальное значение, чтобы значение не могло быть меньше нуля.

2023-10-26 10:28 UTC, vierim commented on src/guides/entities/guide.entity.ts
> +  raiting: number;
Добавь, пожалуйста, минимальное значение, чтобы значение не могло быть меньше нуля.

2023-10-26 10:28 UTC, vierim commented on src/guides/entities/guide.entity.ts
> +  lokation: string;
Правильное название - location.
И вопрос - что делать, если гид работает в нескольких локациях?

2023-10-26 10:28 UTC, vierim commented on src/guides/entities/guide.entity.ts
> +  @IsOptional()
Пересмотри, пожалуйста, описания моделей, так как:
1) использование декоратора `@IsOptional` для любого поля в модели - кажется немного странным. Модель отвеачает за структуру таблицы в базе данных. И столбец в этой таблице - он либо есть, либо нет. Он не может быть только у каких-то отдельных строк.
2) декораторы из библиотеки class-validator можно использовать в рамках DTO, а в моделях все параметры полей обычно пишут в декораторе `@Column`.

2023-11-12 14:31 UTC, Gyxer513 commented
При типизации колонок способом ниже, ORm не может подключиться к базе. 

![image](https://github.com/LiteraExcurs/backend/assets/102280477/4ec5df46-aab5-4e37-9a74-6e49d74e7a6d)

Дока
https://orkhan.gitbook.io/typeorm/docs/entities

2023-11-14 10:14 UTC, vierim approved these changes
Провел второе ревью. Есть несколько моментов, которые надо исправить. Также хорошо бы исправить описание полей базы (ошибка, связанная с length).

2023-11-14 10:14 UTC, vierim commented on src/activity/entities/activity.entity (conflicted copy 2023-10-25 141241).ts
Есть версия, что этот файл лишний.

2023-11-14 10:14 UTC, vierim commented on src/activity/entities/activity.entity.ts
Судя по макету нам нужно еще два поля для вот этих значений - https://disk.yandex.ru/i/_GpVnOS9iQ11kw
На фронте я их назвал subtitle и delay

2023-11-14 10:14 UTC, vierim commented on src/activity/entities/activity.entity.ts
> +  @Column('varchar',{ default: 'example' })
Мне кажется, что это поле стоит сделать уникальным. Тогда мы избежим граблей с одинаковыми урлами у разных экскурсий.

2023-11-14 10:14 UTC, vierim commented on src/activity/entities/activity.entity.ts
> +  @Column('varchar')
Возможно есть смысл сделать это поле enum с ограниченным количеством вариантов значений.

2023-11-14 10:14 UTC, vierim commented on src/activity/entities/activity.entity.ts
>    @IsOptional()
Этот декоратор тут лишний. Он для dto нужен. Суть в том, что колонка в реляционной базе данных либо есть, либо нет. Он не может быть только у некоторых записей. А так как колонка имеет значение по умолчанию, то она не может быть опциональной, у нее всегда будет значение.

2023-11-14 10:14 UTC, vierim commented on src/guides/guides.service.ts
> +    const activity = await this.guidessRepository.findOne({
Мелкая правка - давай переименуем переменную на `guide`.

2023-11-14 10:14 UTC, vierim commented on src/guides/guides.service.ts
> +    throw new NotFoundException('Такой гид уже есть');
Исправь, пожалуйста, текст ошибки на более подходящий

2023-11-14 10:14 UTC, vierim commented on src/guides/guides.service.ts
> +    throw new NotFoundException('Такой гид уже зарегистрирован');
Исправь, пожалуйста, текст ошибки на более подходящий

2023-11-14 10:14 UTC, vierim commented on src/files/files.controller.ts
В обоих контроллерах ты делаешь одинаковые проверки файлов и их подготовку к дальнейшему сохранению. Я бы подумал, как этот функционал можно вынести в отдельный метод, чтобы не дублировать код.
И в целом, наличие логики в контроллере - не очень хороший паттерн. Контроллеры все таки в первую очередь созданы для обработки роутов. А логику принято выносить в сервисы.

2023-11-14 10:21 UTC, Gyxer513 commented on src/files/files.controller.ts
Согласен, под это сделаю отдельную задачу.

2023-11-14 10:24 UTC, Gyxer513 commented on src/activity/entities/activity.entity.ts
Добавлю в задачу по модернизации сущности.

2023-11-14 10:35 UTC, Gyxer513 commented on src/files/files.controller.ts
Под это сделаю отдельную задачу.

2023-11-14 10:36 UTC, merged