Feat/event res
LiteraExcurs/backend pull request #17
Opened 2023-11-29 13:25 UTC by Gyxer513

Проект обновлен

- Добавлены сущности Event, Booking и CRUD методы на них.
- Все логины/пароли перенесены в .env файл.
- Модифицировал Activity.

Обсудил с заказчиком доступность активностей по периодам, решили оставить доступность по сезонам года, в сущности создано соответствующее поле.

2023-11-29 18:45 UTC, vierim requested changes
Отличная работа! Есть небольшие замечания по связям между сущностями, которые желательно поправить. Давай обсудим, если будут вопросы.

2023-11-29 18:45 UTC, vierim commented on .env
Не очень понимаю, почему этот файл подтянулся сюда. Вроде как не должен, судя по .gitignore.

2023-11-29 18:45 UTC, vierim commented on src/booking/entities/booking.entity.ts
> +  activity: number;
Связь с другой сущностью (в данном случае с активностью) все таки желательно делать через встроенный механизм ORM - https://typeorm.io/relations

2023-11-29 18:45 UTC, vierim commented on src/booking/dto/create-booking.dto.ts
> +  price: number;
А вот получать цену с фронта - имхо плохая идея. Может лучше ее брать из активности?

2023-11-29 18:45 UTC, vierim commented on src/booking/dto/create-booking.dto.ts
> +  @ApiProperty({ default: 5 })
Предлагаю добавить валидацию, что число больше нуля.

2023-11-29 18:45 UTC, vierim commented on src/booking/booking.service.ts
> +    await this.bookingRepository.save(query);
Предлагаю сначала проверить, есть ли такая активность в базе вообще, потом проверить не превышает ли новое количество посетителей допустимое для данной активности значение. И только потом добавлять запись booking.

2023-11-29 18:45 UTC, vierim commented on src/booking/booking.service.ts
> +  }
Нам для работы понадобится метод для поиска записи из Booking по каким-то полям. Например, по id активности или по дате. А может даже еще по телефону и email. Желательно предусмотреть более-менее универсальный метод для решения этой задачи.

2023-11-29 18:45 UTC, vierim commented on src/booking/booking.service.ts
> +    await this.bookingRepository.update(id, updateActivityDto);
Перед внесением изменений данные тоже нужно валидировать, как я написал и при создании новой записи в booking.

2023-11-29 18:45 UTC, vierim commented on src/event/entities/event.entity.ts
> +  booked: number;
В данном случае в поле booked мы должны хранить массив элементов Booking. И использовать для этого механизм relations из ORM.

2023-11-29 18:45 UTC, vierim commented on src/event/entities/event.entity.ts
> +  guide: number;
Тоже самое - использование механизма связей из ORM.

2023-11-29 18:45 UTC, vierim commented on src/event/entities/event.entity.ts
> +  avalibleDates: string;
Не очень понимаю, как ты планируешь хранить доступные даты в строке. Может лучше использовать более подходящую сущность, например массив?

2023-11-29 18:45 UTC, vierim commented on src/event/event.controller.ts
> +
Не хватает метода findOne - все таки даже для редактирования в админке, нам сначала надо будет все данные одного элемента Event получить для отображения.

2023-11-29 18:45 UTC, vierim commented on src/event/dto/create-event.dto.ts
> +  booked: number;
Мне кажется, что данный параметр не может прилетать в DTO - он может изменяться только через сущность Booking.

2023-11-30 08:30 UTC, Gyxer513 commented on .env
Действительно, странно.

2023-12-11 19:22 UTC, Gyxer513 commented
Добавил связи, исправил все замечания. 

Во всех сущностях добавил методы поиска по id.

2023-12-13 16:59 UTC, anastasia-bazaeva reviewed
Отличная работа! Связи таблиц работают.
Есть небольшие замечания и вопросы к обсуждению:
- Для админки не хватает информации в методах. Большинство методов findAll сокращены до выборочных полей. Для целей админки это очень ограничивает ее функционал. Также в методах нужны relations с дочерними сущностями для корректной работы.
- Вряд ли нам потребуются методы обновления по slug, т.к. slug - это изменяемое поле, и нам нужно быть уверенными, что мы обновляем именно то, что хотели. Все обновления и удаления стоит делать по id.
- Нам нужно договориться о консистентности данных, которые мы описываем на беке и ожидаем на фронте. У нас есть поля location в сущностях гида и активности, для гида, например, они предзаполняются дефолтным значением 'moscow'. В то время как на фронте мы ожидаем данные loaction в формате либо 'capital' либо 'region'.
- У нас есть поле capacity, которое показывает, сколько человек может записаться на мероприятие. Это поле должно участвовать в расчетах, чтобы мы могли понимать, сможет ли пользователь записаться на мероприятие с тем количеством людей, что он указал, и будет ли доступно мероприятие после того, как очередная запись на него была размещена. 
                      Предлагаю тут два варианта решения задачи: 
                      1. Уменьшать capacity на количество человек, оставивших booking и увеличивать обратно, если заявка booking была удалена. Когда capacity 0, записаться больше нельзя.
                      2. Либо не трогать само поле capacity, и считать, есть ли свободные места вычитая из capacity количество записанных через  booking.

2023-12-13 16:59 UTC, anastasia-bazaeva commented on src/event/dto/create-event.dto.ts
> +  rating: number;
Рейтинг должен будет в последствии рассчитываться как среднее значение из таблицы отзывов, при создании евента это поле нам не понадобится.

2023-12-13 16:59 UTC, anastasia-bazaeva commented on src/booking/booking.service.ts
> +  async create(query: CreateBookingDto) {
Перед созданием записи нам нужно проверить, сколько осталось свободных мест в capacity евента, и хватит ли их для того, чтобы записать нужно количество человек на мероприятие. Если мест не хватит, нужно выдать ошибку, а на фронте научиться ее ловить и правильно отдавать пользователю.

2023-12-13 20:20 UTC, merged