Features/activity resourse
LiteraExcurs/backend pull request #8
Opened 2023-10-17 11:05 UTC by Gyxer513

Привет! Сделал сразу три задачи.

1. Подключил базу
2. Сделал CRUD ресурс с активностью 
3. Сделал возможность загружать файлы ресурс files
4. Добавил Swagger [ссылка ](http://localhost:3000/api) для запуска.

Ниже настройки postman для проверки upload файлов

![image](https://github.com/LiteraExcurs/backend/assets/102280477/ab8cd142-7275-43fe-a8f4-a17c2eafc765)

2023-10-17 20:02 UTC, vierim commented
Не получается запустить проект. Выдает такие ошибки:

![2023-10-17_22-56-38](https://github.com/LiteraExcurs/backend/assets/86350622/ca69f227-6819-4a95-ad6b-9226ef7eee1b)

@Gyxer513 подскажи, мне ведь надо запулить твою ветку, выполнить `npm i` и запускать `npm run start:dev` или я что-то не так делаю?

2023-10-18 05:24 UTC, Gyxer513 commented
> Не получается запустить проект. Выдает такие ошибки:
> 
> ![2023-10-17_22-56-38](https://user-images.githubusercontent.com/86350622/275983544-ca69f227-6819-4a95-ad6b-9226ef7eee1b.png)
> 
> @Gyxer513 подскажи, мне ведь надо запулить твою ветку, выполнить `npm i` и запускать `npm run start:dev` или я что-то не так делаю?

Привет! Извини, видимо глобально поставил зависимости, добавил их в package.json.

2023-10-18 06:40 UTC, vierim commented
@Gyxer513 добавь еще, пожалуйста, в dev зависимости `@types/multer`. И тогда вроде как все заработает.

> Можно доставить их самостоятельно.
Лично мне кажется, что это противоречит концепции код-ревью. Код, который мы проверяем и апрувим, потом отправляется на тесты или в прод. И он должен самостоятельно запускаться, без танцев с бубном в локальном окружении.

2023-10-18 06:42 UTC, Gyxer513 commented
Я просто предложил варианты)

2023-10-18 06:49 UTC, vierim commented
@Gyxer513

2023-10-19 11:00 UTC, vierim commented
Есть несколько замечаний:
1) routName - обычно принято называть такую сущность `slug` (вроде еще из Django пошло).
2) Удаление активности без авторизации работает. Ну это понятно и временно, наверное).
3) Код не отформатирован под преттиер. Желательно сделать.
4) Подключение к базе желательно брать из .env, чтобы при каждом пулле с гита не перписывать доступы к базе (у меня они отличаются от тех, что в проекте).
5) routName: string; - не надо ограничивать 10 символами, надо следить за уникальностью и дать возможность писать туда еще тире. Это нормальная практика когда урл соответствуют названию чего-либо.
6) GET /activity - здесь в ответе разве не надо передавать isActive ?

2023-10-19 12:10 UTC, Gyxer513 commented
> Есть несколько замечаний:
> 
> 1. routName - обычно принято называть такую сущность `slug` (вроде еще из Django пошло).
> 2. Удаление активности без авторизации работает. Ну это понятно и временно, наверное).
> 3. Код не отформатирован под преттиер. Желательно сделать.
> 4. Подключение к базе желательно брать из .env, чтобы при каждом пулле с гита не перписывать доступы к базе (у меня они отличаются от тех, что в проекте).
> 5. routName: string; - не надо ограничивать 10 символами, надо следить за уникальностью и дать возможность писать туда еще тире. Это нормальная практика когда урл соответствуют названию чего-либо.
> 6. GET /activity - здесь в ответе разве не надо передавать isActive ?

1. Исправлено
2. Это временное решение)
3. Исправлено
4. Это тоже временное решение, добавлю конфиг после реализации всех модулей.
5. Исправлено
6. Исправлено

2023-10-20 11:04 UTC, anastasia-bazaeva requested changes
Отличная работа! Все типы запросов к активности работают, обновление активности происходит при отправке только того поля, которое изменяется 👍 
Есть несколько замечаний: 
1. По структуре данных мы ранее обсуждали активность, как более атомарное понятие, которое может переиспользоваться в мероприятиях и дробиться на части с их помощью. В данном же случае мы создаем активности свой урл, т.е. slug, и уходим от концепции переиспользования активностей, т.к. урл должен быть уникальным, а на одну активность могут быть разные мероприятия и разные его части. Если активность - это в итоге конечная сущность, которой будет присваиваться своя уникальная ссылка, то ей не хватает полей с датами, продолжительностью, вместимостью участников и т.д. Если активность остается промежуточным черновиком для использования мероприятиями, то я все же предлагаю хранить урл в мероприятии, т.к. возвращаемой информации по текущей активности нам не хватит для реализации правильного поведения на странице экскурсии.
[Модели данных (1).pdf](https://github.com/LiteraExcurs/backend/files/13053387/1.pdf)

2. Там, где мы решим реализовывать свой урл под экскурсию, нужно будет смягчить требования. Ссылка формируется на основании названия локации, и от 5 букв - это много, т.к. в том же Подмосковье есть такие города, как Клин, Яуза, Нара, Икша, и их названия меньше 5 букв. А если вдруг появятся экскурсии по реке, то Ока, Пра и Уча сразу отпадают. Я бы сразу заложила более мягкое правило на 3 и более символа.

2023-10-20 11:04 UTC, anastasia-bazaeva commented on src/activity/activity.service.ts
> +      },
Когда мы возвращаем список активностей, нужно возвращать их в т.ч. с типом и локацией.

2023-10-20 11:04 UTC, anastasia-bazaeva commented on src/activity/dto/create-activity.dto.ts
> +  isActive: boolean;
Предлагаю создавать сразу активные и не делать поле опциональным, а по умолчанию присваивать значение true. 
Если активность у нас будет использоваться для получения сущностью мероприятия ее данных и фото, то сама активность не отправится прямиком в приложение при получении активного статуса, пока не будет опубликовано мероприятие с ней. Поэтому будет безопасно и удобно сразу отметить активным создаваемое мероприятие, т.к. в боевой версии его создание чаще всего будет означать добавление именно активной и доступной записи для использования в публикации мероприятия.

2023-10-23 07:15 UTC, merged